"""initial schema

Revision ID: 72b637874228
Revises: 
Create Date: 2026-09-06 23:04:46.652053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b637874228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('injected_failure', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('adk_session_id', sa.String(), nullable=True),
    sa.Column('adk_invocation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_trace',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=False),
    sa.Column('affected_table', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('migration_sql', sa.Text(), nullable=True),
    sa.Column('rollback_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('changed_sample', sa.JSON(), nullable=True),
    sa.Column('dry_run_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('incident')
    op.drop_table('agent_trace')
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
